"""review 테이블 user_name 컬럼 추가

Revision ID: 54dfea32c7cc
Revises: 
Create Date: 2021-11-22 03:59:49.784224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dfea32c7cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_name', sa.String(length=30)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'user_name')
    # ### end Alembic commands ###
